"""words, word_links, error_pattern_links

Revision ID: 15e0b1d86ddd
Revises: 21fbbfd778ac
Create Date: 2026-08-01 22:04:51.667918
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "15e0b1d86ddd"
down_revision: str | None = "21fbbfd778ac"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "words",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("lemma", sa.String(length=120), nullable=False),
        sa.Column("lemma_raw", sa.String(length=240), nullable=False),
        sa.Column("pos", sa.String(length=16), nullable=False),
        sa.Column("article", sa.String(length=8), nullable=True),
        sa.Column("plural", sa.String(length=80), nullable=True),
        sa.Column("verb_prefix", sa.String(length=40), nullable=True),
        sa.Column("verb_infinitive", sa.String(length=80), nullable=True),
        sa.Column("verb_aux", sa.String(length=8), nullable=True),
        sa.Column("example_de", sa.Text(), nullable=True),
        sa.Column("translation_en", sa.Text(), nullable=False),
        sa.Column("level", sa.String(length=8), nullable=False),
        sa.Column("chapter", sa.Integer(), nullable=True),
        sa.Column("chapter_title", sa.String(length=200), nullable=True),
        sa.Column("topic", sa.String(length=200), nullable=True),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("source_page", sa.Integer(), nullable=True),
        sa.Column("needs_review", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_words")),
        sa.UniqueConstraint("lemma", "pos", "level", name=op.f("uq_words_lemma")),
    )
    with op.batch_alter_table("words", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_words_lemma"), ["lemma"], unique=False)
        batch_op.create_index(batch_op.f("ix_words_level"), ["level"], unique=False)
        batch_op.create_index(batch_op.f("ix_words_source"), ["source"], unique=False)
        batch_op.create_index(batch_op.f("ix_words_topic"), ["topic"], unique=False)

    op.create_table(
        "error_pattern_links",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("error_type", sa.String(length=80), nullable=False),
        sa.Column("word_id", sa.Integer(), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["word_id"],
            ["words.id"],
            name=op.f("fk_error_pattern_links_word_id_words"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_error_pattern_links")),
        sa.UniqueConstraint(
            "error_type", "word_id", name=op.f("uq_error_pattern_links_error_type")
        ),
    )
    with op.batch_alter_table("error_pattern_links", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_error_pattern_links_error_type"),
            ["error_type"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_error_pattern_links_word_id"), ["word_id"], unique=False
        )

    op.create_table(
        "word_links",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("from_word_id", sa.Integer(), nullable=False),
        sa.Column("to_word_id", sa.Integer(), nullable=False),
        sa.Column("edge_type", sa.String(length=24), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("citation", sa.Text(), nullable=True),
        sa.Column("detail", sa.String(length=40), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "source != 'llm' OR (citation IS NOT NULL AND citation != '')",
            name=op.f("ck_word_links_llm_edge_cited"),
        ),
        sa.ForeignKeyConstraint(
            ["from_word_id"],
            ["words.id"],
            name=op.f("fk_word_links_from_word_id_words"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["to_word_id"],
            ["words.id"],
            name=op.f("fk_word_links_to_word_id_words"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_word_links")),
        sa.UniqueConstraint(
            "from_word_id",
            "to_word_id",
            "edge_type",
            name=op.f("uq_word_links_from_word_id"),
        ),
    )
    with op.batch_alter_table("word_links", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_word_links_edge_type"), ["edge_type"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_word_links_from_word_id"), ["from_word_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_word_links_to_word_id"), ["to_word_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("word_links", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_word_links_to_word_id"))
        batch_op.drop_index(batch_op.f("ix_word_links_from_word_id"))
        batch_op.drop_index(batch_op.f("ix_word_links_edge_type"))

    op.drop_table("word_links")
    with op.batch_alter_table("error_pattern_links", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_error_pattern_links_word_id"))
        batch_op.drop_index(batch_op.f("ix_error_pattern_links_error_type"))

    op.drop_table("error_pattern_links")
    with op.batch_alter_table("words", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_words_topic"))
        batch_op.drop_index(batch_op.f("ix_words_source"))
        batch_op.drop_index(batch_op.f("ix_words_level"))
        batch_op.drop_index(batch_op.f("ix_words_lemma"))

    op.drop_table("words")
    # ### end Alembic commands ###
