"""error_logs.explanation

Revision ID: 21fbbfd778ac
Revises: c5ce82673832
Create Date: 2026-07-27 11:46:32.145388
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "21fbbfd778ac"
down_revision: str | None = "c5ce82673832"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("error_logs", schema=None) as batch_op:
        batch_op.add_column(sa.Column("explanation", sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("error_logs", schema=None) as batch_op:
        batch_op.drop_column("explanation")

    # ### end Alembic commands ###
