"""sessions, error_logs, immersion_logs

Revision ID: c5ce82673832
Revises: 
Create Date: 2026-07-26 15:25:49.763725
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'c5ce82673832'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('scenario', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sessions'))
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sessions_started_at'), ['started_at'], unique=False)

    op.create_table('error_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('error_type', sa.String(length=80), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('utterance', sa.Text(), nullable=False),
    sa.Column('correction', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('fk_error_logs_session_id_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_error_logs'))
    )
    with op.batch_alter_table('error_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_error_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_error_logs_error_type'), ['error_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_error_logs_session_id'), ['session_id'], unique=False)

    op.create_table('immersion_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('minutes', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(length=280), nullable=True),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('fk_immersion_logs_session_id_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_immersion_logs'))
    )
    with op.batch_alter_table('immersion_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_immersion_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_immersion_logs_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_immersion_logs_source'), ['source'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('immersion_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_immersion_logs_source'))
        batch_op.drop_index(batch_op.f('ix_immersion_logs_session_id'))
        batch_op.drop_index(batch_op.f('ix_immersion_logs_created_at'))

    op.drop_table('immersion_logs')
    with op.batch_alter_table('error_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_error_logs_session_id'))
        batch_op.drop_index(batch_op.f('ix_error_logs_error_type'))
        batch_op.drop_index(batch_op.f('ix_error_logs_created_at'))

    op.drop_table('error_logs')
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sessions_started_at'))

    op.drop_table('sessions')
    # ### end Alembic commands ###
